import os
import subprocess

def clone_or_update_repo(repo_url, local_dir):
    """
    Clones the GitHub repository if it doesn't exist, or fetches the latest changes if it does.
    
    This function was generated by AI, as the user shoud not manually download all the data from the repository.
    An external storage is also needed for the  server. That is why a conncection between server and repository is needed.

    Parameters
    ----------
    repo_url : str
        The URL of the GitHub repository.
    local_dir : str
        The local directory where the repository should be cloned.

    Returns 
    -------
    None

    Raises
    ------
    subprocess.CalledProcessError
        If the `git` command fails.
    """
    print("Loading and preparing data...")
    if os.path.exists(local_dir):
        print(f"Updating existing repository in {local_dir}...")
        try:
            subprocess.run(['git', 'fetch'], cwd=local_dir, check=True)
            changes = subprocess.run(['git', 'status', '-uno'], cwd=local_dir, check=True, capture_output=True, text=True)
            if 'Your branch is up to date' not in changes.stdout:
                subprocess.run(['git', 'pull'], cwd=local_dir, check=True)
            else:
                print("No updates available.")
        except subprocess.CalledProcessError as e:
            print(f"Failed to update the repository: {e}")
    else:
        print(f"Cloning repository from {repo_url} into {local_dir}...")
        subprocess.run(['git', 'clone', repo_url, local_dir], check=True)

def setup_repo(repo_url, local_dir):
    """
    Sets up the repository by cloning or updating it.

    Parameters
    ----------
    repo_url : str
        The URL of the GitHub repository.
    local_dir : str
        The local directory where the repository should be cloned.

    Returns
    -------
    str
        The path to the local directory where the repository is set up.
    """
    print(f"Setting up repository at {local_dir}...")
    clone_or_update_repo(repo_url, local_dir)
    return local_dir

# Example usage
repo_url = 'https://github.com/aleksandar42/webapp.git'
local_dir = os.path.join(os.path.expanduser('~'), 'webapp')
setup_repo(repo_url, local_dir)
